Repository wanted-team2/3week_ncnc, pull requests merged in 2022-02, with the labels that each got.

#14 :bug: Fix: font 변환
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.eot
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.woff
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.woff2
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.eot
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.woff
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.woff2
  styles/globalStyle.ts
Labels: Fix

#15 ✨ Feat: CategoryList 구현
  components/Category/Category.tsx
  components/Category/Style.ts
  components/CategoryList/CategoryList.tsx
  components/CategoryList/Style.ts
  components/index.ts
Labels: Feat

#9 ✨ Feat: NavigationBar 구현
  .eslintrc.js
  components/base/NavigationBar/NavigationBar.tsx
  components/base/NavigationBar/Style.ts
  components/base/NavigationItem/NavigationItem.tsx
  components/base/NavigationItem/Style.ts
  components/base/index.ts
  package.json
Labels: Feat

#12 ✨ Feat: ProductionItem 컴포넌트 구현
  .eslintrc.js
  components/base/ProductionImage/ProductionImage.tsx
  components/base/ProductionInfo/ProductionInfo.tsx
  components/base/ProductionInfo/Style.ts
  components/base/index.ts
  components/domain/ProductionItem/ProductionItem.tsx
  components/domain/ProductionItem/Style.ts
  components/domain/ProductionList/ProductionList.tsx
  components/domain/ProductionList/Style.ts
  components/domain/index.ts
  next.config.js
  utils/fucntions/index.ts
Labels: Feat

#16 :sparkles: Feat: Header, Drawer 구현
  components/base/Header/Header.tsx
  components/base/Header/Style.ts
  components/base/MenuBar/MenuBar.tsx
  components/base/MenuBar/Style.ts
  components/base/MenuImage/MenuImage.tsx
  components/base/index.ts
Labels: UI, Feat

#19 ✨ Feat: Contact, Categories, Home Page get~~Props 구현
  api/index.ts
  hooks/index.ts
  hooks/useAxios.ts
  package.json
  pages/categories/[categoryId].tsx
  pages/contacts/index.tsx
  pages/index.tsx
  types/Brand.ts
  types/Category.ts
  types/ConItem.ts
  types/Nested.ts
  types/QaType.ts
  types/Qas.ts
  types/SoonItem.ts
  types/index.ts
Labels: Feat

#18 ✨ Feat: OptionBox 구현
  components/CheckedOption/CheckedOption.tsx
  components/CheckedOption/Style.ts
  components/Option/Option.tsx
  components/Option/Style.ts
  components/OptionBox/OptionBox.tsx
  components/OptionBox/Style.ts
  components/index.ts
  hooks/index.ts
  hooks/useOption.ts
Labels: Feat

#28 ♻️ Refactor: 카테고리 컴포넌트 개편 및 타입 컨벤션 변경
  api/index.ts
  components/base/Category/Category.tsx
  components/base/CategoryList/CategoryList.tsx
  components/base/NavigationBar/NavigationBar.tsx
  components/base/NavigationBar/Style.ts
  components/base/NavigationItem/NavigationItem.tsx
  types/index.ts
Labels: Refactor

#31 :bug: Fix: OTS parsing error 수정 on globalStyles
  styles/globalStyle.ts
Labels: Fix

#17 Feat: Swiper 컴포넌트 구현, useSwipe, useWindowWidth 훅 구현
  components/domain/Pagination/Pagination.tsx
  components/domain/Pagination/Style.ts
  components/domain/Swiper/Style.ts
  components/domain/Swiper/Swiper.tsx
  components/domain/index.ts
  hooks/index.ts
  hooks/useSwipe.tsx
  hooks/useWindowWidth.tsx
  styles/commonStyle.ts
  styles/font.ts
Labels: Feat

#37 :bug: Fix: Category 스타일 수정
  components/base/Category/Category.tsx
  components/base/Category/Style.ts
  components/base/CategoryList/Style.ts
Labels: UI, Fix

#34 ✨ Feat: Contacts 페이지 구현, overflow 이슈 미해결
  components/base/ContactTab/ContactTab.tsx
  components/base/ContactTab/Style.ts
  components/base/MenuBar/Style.ts
  components/base/index.ts
  components/domain/Dropdown/Style.ts
  components/domain/DropdownList/DropdownList.tsx
  hooks/index.ts
  hooks/useClickedId.tsx
  hooks/useTabs.tsx
  pages/contacts/Style.ts
  pages/contacts/index.tsx
  styles/commonCompo.tsx
  styles/font.ts
  styles/globalStyle.ts
Labels: UI, Feat

#32 ✨ Feat: main 페이지 구현
  components/base/Header/Header.tsx
  components/base/Header/Style.ts
  components/base/MenuBar/Style.ts
  components/base/ProductionImage/ProductionImage.tsx
  components/base/ProductionInfo/ProductionInfo.tsx
  components/domain/ProductionList/ProductionList.tsx
  components/domain/index.ts
  pages/Style.ts
  pages/index.tsx
  styles/font.ts
Labels: UI, Fix, Feat

#40 :bug: Fix: getDiscount 함수 적용
  components/base/Option/Option.tsx
  components/base/OptionBox/OptionBox.tsx
  pages/items/[itemId].tsx
Labels: Fix

#43 ♻️ Refactor: Swiper 데이터 api 요청 처리, resize 시 애니메이션 끄기 처리
  components/domain/Pagination/Pagination.tsx
  components/domain/Swiper/Style.ts
  components/domain/Swiper/Swiper.tsx
  hooks/useSwipe.tsx
  public/mock/slideLIst.json
  types/Swipe.ts
  types/index.ts
Labels: Refactor

#49 :bug: Fix: 문자데이터 분리
  components/domain/OptionBox/OptionBox.tsx
  components/domain/index.ts
Labels: Fix

#50 :bug: Fix: Category 변경된 코드 복원
  components/base/Category/Style.ts
  components/base/OptionBox/Style.ts
Labels: Fix
